export const DEFAULT_FABRIC_PRODUCTS = [
  {
    id: "fabric-loose-velvet",
    title: "Premium Royal Velvet Loose Sofa Cloth (By the Meter)",
    slug: "factory-loose-velvet-sofa-cloth",
    price: 850,
    compareAtPrice: 1200,
    woodType: "Heavy-Duty Velvet Cloth",
    dimensions: "Width: 54 inches (Sold by Meter)",
    finishType: "Water-Repellent Velvet Finish",
    materialPurity: "100% Pure Quality",
    stock: 250,
    showInquiryBtn: true,
    showDetailsBtn: true,
    Category: { id: "cat-fabrics", slug: "fabrics", name: "Loose Cloth & Fabrics" },
    images: [
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Authentic raw loose velvet fabric stored in rolls directly at our Solapur manufacturing facility. 450 GSM, stain-resistant, and ideal for custom living room sofas and cushion covers.",
  },
  {
    id: "fabric-loose-jacquard",
    title: "Turkish Floral Jacquard Loose Furniture Cloth Roll",
    slug: "turkish-jacquard-loose-furniture-cloth",
    price: 1250,
    compareAtPrice: 1750,
    woodType: "Turkish Jacquard Fabric",
    dimensions: "Width: 56 inches (Sold by Meter)",
    finishType: "Heirloom Woven Texture",
    materialPurity: "100% Pure Quality",
    stock: 180,
    showInquiryBtn: true,
    showDetailsBtn: true,
    Category: { id: "cat-fabrics", slug: "fabrics", name: "Loose Cloth & Fabrics" },
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Heavy woven royal jacquard loose cloth from our factory textile stock. High Martindale rub count engineered for longevity and luxurious sofa upholstery.",
  },
  {
    id: "fabric-loose-chenille",
    title: "Textured Chenille & Breathable Cotton Sofa Material",
    slug: "textured-chenille-cotton-sofa-material",
    price: 950,
    compareAtPrice: 1350,
    woodType: "Chenille-Cotton Blend",
    dimensions: "Width: 54 inches (Sold by Meter)",
    finishType: "Soft Matte Texture",
    materialPurity: "100% Pure Quality",
    stock: 320,
    showInquiryBtn: true,
    showDetailsBtn: true,
    Category: { id: "cat-fabrics", slug: "fabrics", name: "Loose Cloth & Fabrics" },
    images: [
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Breathable textured chenille loose cloth stored at the factory. Highly durable, easy to wash, and perfect for daily-use sofa sets and accent armchairs.",
  },
];
